// Generated by IcedCoffeeScript 1.2.0t
(function() {
  var LoginToken, Photo, PostItem, Settings, User, Validator, app, certificate, emitter, express, formidable, fs, generateResponse, io, key, logger, nib, path, service, settings, socket, socketIOPort, stylus, sys, url, _;

  sys = require('util');

  express = require('express');

  path = require('path');

  url = require('url');

  fs = require('fs');

  _ = require('underscore');

  stylus = require('stylus');

  nib = require('nib');

  Settings = require('settings');

  formidable = require('formidable');

  Validator = require('validator').Validator;

  settings = new Settings(path.join(__dirname, 'config/environment.js')).getEnvironment();

  key = settings.key;

  certificate = settings.certificate;

  service = require('./util/service');

  generateResponse = service.generateResponse;

  logger = service.logger;

  PostItem = service.PostItem;

  Photo = service.Photo;

  User = service.User;

  LoginToken = service.LoginToken;

  emitter = service.emitter;

  socketIOPort = service.socketIOPort;

  Validator.prototype.error = function(msg) {
    return this._errors.push(msg);
  };

  Validator.prototype.getErrors = function() {
    return this._errors;
  };

  app = express.createServer();

  app.helpers(require('./util/helpers.js').helpers);

  app.dynamicHelpers(require('./util/helpers.js').dynamicHelpers);

  console.log("emitter");

  io = require('socket.io-client');

  socket = io.connect("http://localhost:8080/new.york.ny.us", {
    'force new connection': true
  });

  socket.emit("postitem:published", {
    address: {
      city: "ta",
      state: "teadf",
      country: "fdafdafd"
    }
  });

  socket.disconnect();

  app.listen(7576);

}).call(this);
